apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
  labels:
    app: nginx
    tier: frontend
spec:
  # Pod template
  template:
    metadata:
      name: nginx
      labels:
        app: nginx-webserver
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.1
          ports:
            - containerPort: 80 # Nginx is listening on port 80 (see docs on Docker if you are unsure)
  selector:
    matchLabels:
      app: nginx-webserver
  replicas: 5
