apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: NodePort
  ports:
    - port: 80 # This is the port that the service will listen on i.e http://localhost:80 and send traffic to the targetPort
      targetPort: 80 # This is the port that the container exposes and the service will send traffic to i.e Nginx is listening on port 80, so we will send traffic to port 80
      nodePort: 30080 # This is the port that will be exposed on the nodes that we will hit, i.e http://localhost:30080 (port range is 30000-32767)
  # This is the selector that will match the labels in the deployment / pod template of the app that we want to expose, in this case nginx
  # If we are selecting from a pod.yaml, then it is a label in the metadata, else it is the label in the pod template of the deployment
  selector:
    app: nginx-webserver
