apiVersion: v1 # api version of the object
kind: Pod # kind of Kubernetes object
metadata:
  name: postgres #name of the pod
  labels:
    tier: db-tier

# The spec section defines the containers that should be run in the pod.
spec:
  containers:
    - name: postgres
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: 'postgres'
      ports:
        - containerPort: 5432
          name: postgres
