apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx-webserver # select the nginx pods
  ports:
    - port: 80
      targetPort: 80 # Port that the pod definition listens on, in this case, Nginx pod
